spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb?DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    password: password
  application:
    name: rock-paper-scissor-boot
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: user
      password: user